Javascript initiates download directly from the browser now
heritagefund/salesforce-playground pull request #1
Opened 2020-09-14 12:47 UTC by ptrelease

2020-09-14 13:27 UTC, stuartmccoll requested changes

2020-09-14 13:27 UTC, stuartmccoll commented on force-app/main/default/classes/AzureBlobStorageController.cls
> +        String key = 'SECRET KEY';
Can we keep this as `ACCESS_KEY`? I put it in as that so that if we don't pick this up again for a while then `ACCESS_KEY` tells you exactly what you're looking for in Azure.

2020-09-14 13:27 UTC, stuartmccoll commented on force-app/main/default/classes/AzureBlobStorageController.cls
> +    global static String getFormattedTimestamp() {
Did this need to change to `global`?

2020-09-14 13:27 UTC, stuartmccoll commented on force-app/main/default/classes/AzureBlobStorageController.cls
> +    global static String constructSharedKey(String timestamp, String storageAccountName, String containerName, String fileName) {
Did this need to change to `global`?

2020-09-14 13:27 UTC, stuartmccoll commented on force-app/main/default/lwc/listCustomAttachments/listCustomAttachments.js
> +    async startDownloadWithHTTPGetFromAzure(caseId, documentType, fileName) {
Did this need to be `async`? Wasn't sure if it was something we changed whilst testing and forgot to put back.

2020-09-14 13:27 UTC, stuartmccoll commented on force-app/main/default/lwc/listCustomAttachments/listCustomAttachments.js
> +        xhr.setRequestHeader('Authorization', 'SharedKey STORAGE_ACCOUNT:' + this.sharedKey);
Change `STORAGE_ACCOUNT` to `STORAGE_ACCOUNT_NAME`.

2020-09-14 13:27 UTC, stuartmccoll commented on force-app/main/default/lwc/listCustomAttachments/listCustomAttachments.js
> +            if (this.status == 200) {
```suggestion
            if (this.status === 200) {
```

2020-09-14 13:49 UTC, ptrelease commented on force-app/main/default/lwc/listCustomAttachments/listCustomAttachments.js
> +    async startDownloadWithHTTPGetFromAzure(caseId, documentType, fileName) {
It _will_ go.  But for now we need it for ```await new Promise(r => setTimeout(r, 5000));```

2020-09-15 06:49 UTC, stuartmccoll commented on force-app/main/default/classes/AzureBlobStorageController.cls
> +    global static String getFormattedTimestamp() {
There is no comment below 🕵️.

2020-09-15 08:49 UTC, stuartmccoll approved these changes

2020-09-15 08:51 UTC, merged